rule_files:
  - /etc/prometheus/alert.rules
scrape_configs:
  - job_name: "node"
    scrape_interval: "15s"
    file_sd_configs:
    - files:
      - /opt/dynamic-prometheus-inventory/linux_hosts.json

  - job_name: 'snmp'
    file_sd_configs:
    - files:
      - /opt/dynamic-prometheus-inventory/mikrotik_hosts.json
    metrics_path: /snmp
    params:
      module: [mikrotik_routeros]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "{{ inventory_hostname }}:9116"

  - job_name: 'ping-everything'
    metrics_path: /probe
    params:
      module: [icmp]  # Look for a HTTP 200 response.
    file_sd_configs:
    - files:
      - /opt/dynamic-prometheus-inventory/MemHamWAN_hosts.json
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: "{{ inventory_hostname }}:9115"  # Blackbox exporter.
