# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).


scrape_configs:
- job_name: 'blackbox'
  metrics_path: /probe
  params:
    module: [icmp]  # Look for a HTTP 200 response.
  file_sd_configs:
  - files:
    - /opt/dynamic-prometheus-inventory/MemHamWAN_hosts.json
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox_exporter:9115  # Blackbox exporter.
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  file_sd_configs:
  - files:
    - /opt/dynamic-prometheus-inventory/linux_hosts.json
- job_name: 'snmp'
  file_sd_configs:
  - files:
    - /opt/dynamic-prometheus-inventory/mikrotik_hosts.json
  metrics_path: /snmp
  params:
    module: [mikrotik]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: snmp_exporter:9116  # SNMP exporter.
