version: "3.1"
services:
  grafana: #TODO: make data persist via volume
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_ADMIN_PASSWORD: admin
    deploy:
      replicas: 1
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
    secrets:
      - prometheus_config
    entrypoint:
      - /bin/prometheus
      - -config.file=/run/secrets/monitoring_prometheus_config
      - -storage.local.path=/prometheus
      - -web.console.libraries=/etc/prometheus/console_libraries
      - -web.console.templates=/etc/prometheus/consoles
  blackbox_exporter:
    image: prom/blackbox-exporter
    deploy:
      mode: global
    ports:
      - "9115:9115"
  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    deploy:
      mode: global

secrets:
   prometheus_config:
     file: ../prometheus/prometheus-config.yml
