version: "3.1"
networks:
  utility_exporters:
  prometheus:
services:
  grafana: #TODO: make data persist via volume
    image: k0ret/grafana-runonce
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_ADMIN_PASSWORD: admin
      DOCKER_SECRET_NAME: grafana_run_once
    deploy:
      replicas: 1
    networks:
      - prometheus
    secrets:
      - grafana_run_once
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
    secrets:
      - prometheus_config
    entrypoint:
      - /bin/prometheus
      - -config.file=/run/secrets/prometheus_config
      - -storage.local.path=/prometheus
      - -web.console.libraries=/etc/prometheus/console_libraries
      - -web.console.templates=/etc/prometheus/consoles
#      - -web.route-prefix=/prometheus
    networks:
      - utility_exporters
      - prometheus
    volumes:
      - dynamic-prometheus-inventory:/opt/dynamic-prometheus-inventory
  blackbox_exporter:
    image: prom/blackbox-exporter
    deploy:
      replicas: 2
    expose:
      - "9115"
    networks:
      - utility_exporters
  snmp_exporter:
    image: prom/snmp-exporter
    deploy:
      replicas: 2
    expose:
      - "9116"
    networks:
      - utility_exporters
    secrets:
      - snmp_exporter_config
    entrypoint:
      - /bin/snmp_exporter
      - --config.file=/run/secrets/snmp_exporter_config
  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - "8080"
    deploy:
      mode: global
  haproxy:
    image: haproxy:alpine
    networks:
      - prometheus
    secrets:
      - haproxy_config
    ports:
      - "80:80"
    command:
      - haproxy
      - -f
      - /run/secrets/haproxy_config
  dynamic-inventory:
    image: k0ret/hamwan-dynamic-inventory
    environment:
      PORTAL_ANSIBLE_URL: https://portal.memhamwan.net/host/ansible.json
    volumes:
      - dynamic-prometheus-inventory:/var/hamwan-inventory/
#TODO: add another service that just runs my loop

volumes:
  dynamic-prometheus-inventory:

secrets:
  prometheus_config:
   file: ./prometheus/prometheus-config.yml
  snmp_exporter_config:
    file: ./prometheus/snmp.yml
  grafana_run_once:
    file: ./prometheus/grafana_run_once.sh
  haproxy_config:
    file: ./prometheus/haproxy
