version: "3.1"
services:
  grafana: #TODO: make data persist via volume
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_ADMIN_PASSWORD: admin
    deploy:
      replicas: 1
    volumes:
      - /srv/monitoring-grafana:/var/lib/grafana
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
    volumes:
      - /srv/monitoring-prometheus:/prometheus
  blackbox_exporter:
    image: prom/blackbox-exporter
    deploy:
      mode: global
    ports:
      - "9115:9115"
  postgres:
    image: postgres:9.5
    volumes:
      - /srv/monitoring-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    deploy:
      mode: global
